### PR TITLE
Add create:class command

### PR DESCRIPTION
**Pull request by rezalaal**

### CODE REVIEW

**Comment by LukeTowers** [comment]
I'm not sure a scaffolding command is needed for generating a single file that wouldn't have any boilerplate, could you expand on your reasons for wanting this included?

**Comment by rezalaal** [comment]
There are many times when we create a class and encounter the error that the class was not found. Because it is sensitive to letters or for other reasons. In this way, both the construction of the class is available and typing errors are prevented when creating the class, and this command can be extended in the future.
Thank you

**Comment by LukeTowers** [comment]
The class not found errors, do you get them when you name the directory Classes instead of classes? If so we can probably instead tweak the autoloading code to allow for both forms since I know titled case folders are common in other projects.

**Comment by rezalaal** [comment]
Yes I get it when class name and class folder  are same.

**Comment by LukeTowers** [comment]
Can you provide a specific example of a class that fails to load in Winter with the exact path to the class and the contents of the class file? This sounds like a separate issue that adding a scaffolding command doesn't really fix.

**Comment by rezalaal** [comment]
Now that I want to send a sample, everything works fine ;-)

**Comment by LukeTowers** [comment]
@rezalaal of course 😉 I'll close this for now but feel free to submit a new issue if you encounter issues in the future!

**Pull request closed without merging**
