### PR TITLE
Prevent empty id attribute

### PR DESCRIPTION
**Pull request by mjauvin**
Replaces #142

Add unit tests

### CODE REVIEW

**Comment by mjauvin** [comment]
You were right @LukeTowers, using isset() was not correct in this case.

This version resolves the issue.

**Comment by AIC-BV** [comment]
Thanks @mjauvin

**Comment by mjauvin** [comment]
Does that PR solve your issue @AIC-BV ?

**Comment by AIC-BV** [comment]
> Does that PR solve your issue @AIC-BV ?

Yes, it removes all these warnings, thus removing the w3c errors
image

**Comment by mjauvin** [comment]
It's not clear from the screenshot you referenced above... glad to hear it works!

**Comment by AIC-BV** [comment]
> It's not clear from the screenshot you referenced above... glad to hear it works!

Well the screenshot is the before, there is no after because it's empty😂

**Comment by LukeTowers** [comment]
@bennothommo can we fix the code analysis tests?

**Review by LukeTowers — APPROVED** [review]

**Pull request merged**
