### PR TITLE
Add config['local_domain'] for smtp transport (default is [127.0.0.1])

### PR DESCRIPTION
**Pull request by mjauvin**
Without this, connecting to google smtp relay server fails with SMTP code 421 after the HELO command.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@mjauvin could you add a comment giving more background information?

**Comment by mjauvin** [comment]
@LukeTowers You mean a comment in the source code itself?

**Comment by LukeTowers** [comment]
Yes. Also what tests are failing? Can @jaxwilko or @bennothommo take a look at them?

**Comment by LukeTowers** [comment]
@mjauvin and what's the benefit of this change over just telling users to set the `local_domain` property correctly?

**Comment by mjauvin** [comment]
@LukeTowers Do you mean users setting this in their `config/mail.php` file ?

**Comment by LukeTowers** [comment]
Yes

**Comment by mjauvin** [comment]
@LukeTowers I find it's a sensible default for the Storm library in general, many smtp server will fail with the current symfony default.

**Comment by LukeTowers** [comment]
Could you explain what exactly it's doing? I've never used any of those functions

**Comment by mjauvin** [comment]
In the SMTP protocol, the HELO command is the first greeting from the client and it announces where it's connecting from. The SMTP server will usually (but not always) use this information to verify that this hostname matches the reverse lookup from the IP it connected from.

My code is setting the local_domain mail config option. This is querried later by the EsmtpTransportFactory like this:
(see symfony/mailer/Transport/Smtp/EsmtpTransportFactory.php)
```
        if (null !== ($localDomain = $dsn->getOption('local_domain'))) {
            $transport->setLocalDomain($localDomain);
        }
```
And is used in the EHLO command here:
(see symfony/mailer/Transport/Smtp/EsmtpTransport.php)
```
    protected function doHeloCommand(): void
    {   
        try {
            $response = $this->executeCommand(sprintf("EHLO %s\r\n", $this->getLocalDomain()), [250]);
        } catch (TransportExceptionInterface $e) {
            parent::doHeloCommand();

            return;
        }
        ...
```
And for the HELO command here:
(see symfony/mailer/Transport/Smtp/SmtpTransport.php
```
    protected function doHeloCommand(): void
    {   
        $this->executeCommand(sprintf("HELO %s\r\n", $this->domain), [250]);
    }       
```

**Comment by mjauvin** [comment]
Those tests are failing @LukeTowers:
```
1) QueryBuilderTest::testUpsert
Error: Call to undefined method Mock_ConnectionInterface_f1a1bb84::getConfig()

/home/runner/work/storm/storm/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php:203
/home/runner/work/storm/storm/src/Database/QueryBuilder.php:347
/home/runner/work/storm/storm/tests/Database/QueryBuilderTest.php:106

2) QueryBuilderTest::testUpsertWithUpdateColumns
Error: Call to undefined method Mock_ConnectionInterface_f1a1bb84::getConfig()

/home/runner/work/storm/storm/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php:203
/home/runner/work/storm/storm/src/Database/QueryBuilder.php:[34](https://github.com/wintercms/storm/runs/6263996814?check_suite_focus=true#step:10:34)7
/home/runner/work/storm/storm/tests/Database/QueryBuilderTest.php:149
```

**Comment by mjauvin** [comment]
This is not viable, better to set directly in smtp driver config if needed.

**Comment by LukeTowers** [comment]
@mjauvin could you give some more details why this isn't viable? Is there anything that we can add to the config file comment to better help people with the same issue?

**Pull request closed without merging**
