### PR TITLE
Most relations were missing getRelationName method.

### PR DESCRIPTION
**Pull request by mjauvin**
Add missing getter for protected `relationName` property.

### CODE REVIEW

**Comment by mjauvin** [comment]
I wish the different Relation classes would have a common base to add the common properties/methods to... this is all over the place.

**Comment by mjauvin** [comment]
How could we call a new Concern shared by all relations to include the `protected $relationName` / `getRelationName()` to (and other common properties/methods) ?

**Comment by bennothommo** [comment]
@mjauvin I think I did this work already in the Laravel Relations PR. :)

**Comment by mjauvin** [comment]
Included in #167

**Pull request closed without merging**
