### PR TITLE
Allow for YAML rendering pre/post processing.

### PR DESCRIPTION
**Pull request by bennothommo**
This is a BC break since it changes the contract. Classes implementing the `Winter\Storm\Parse\Processor\Contracts\YamlProcessor` interface should instead extend the `Winter\Storm\Parse\Processor\YamlProcessor` abstract to maintain parity with the interface.

This change is in preparation of a change that I intend to make for the Builder plugin to ensure that the `version.yaml` uses quoted version keys when generating the migrations.

### CODE REVIEW

**Comment by LukeTowers** [comment]
How does this interact with #21 and the related PR?

**Comment by bennothommo** [comment]
It should be entirely compatible with that PR (besides changing the processor to extend the abstract class as opposed to implementing the interface). These new methods are for rendering though, so while that PR ensures that our older version files can still be read, this will allow us to ensure that the YAML files are correctly written as well.

**Comment by LukeTowers** [comment]
@bennothommo what's the status of this?

**Comment by bennothommo** [comment]
@LukeTowers it should be ready to go.

**Comment by LukeTowers** [comment]
@bennothommo looks like the tests need to be fixed for this PR

**Comment by bennothommo** [comment]
@LukeTowers fixed up the tests

**Pull request merged**
