### PR TITLE
Improved gif file resizing in media manager

### LINKED ISSUE #87: Media manager throwing error while trying to resize gif image
- Winter CMS Build: v1.1.2
- PHP Version: 8.0.3 (issue probably related to PHP 8)
- Database Engine: SQLite [not related to DB engine]
- Plugins Installed: [not related to plugins]

### Description:
CMS back-end Media manager throws

`Symfony\Component\Debug\Exception\FatalThrowableError: imagecolorsforindex(): Argument #2 ($color) is out of range in /srv/bucketbear.club/vendor/winter/storm/src/Database/Attach/Resizer.php:127`

error (and shows error popup - 1) when trying to generate thumbnail image of gif image. No thumbnail image is generated at the end - the loading indicator is executing infinitely (2) and the same behavior happens again if clicking on image later.

Preview of issue:
gif_issue

### Steps To Reproduce:
1. Open CMS Media manager;
2. Upload gif image, for example, [Example image 1](https://bb.ala.lv/storage/app/media/bears/9.gif) or [Example image 2](https://bb.ala.lv/storage/app/media/bears/10.gif) - although probably many gif images are affected;
3. Click on uploaded image into Media manager to view file info and preview - error is thrown.

### Additional Info And Possible Fixes:

Probably this issue is similar as described in [ProcessWire imagecolorsforindex(): Argument #2 ($color) is out of range](https://github.com/processwire/processwire-issues/issues/1299) and [StackOverflow: What could cause a “color index out of range” error for imagecolorsforindex()?](https://stackoverflow.com/questions/3874533/what-could-cause-a-color-index-out-of-range-error-for-imagecolorsforindex)

For experimenting purposes I was trying to modify 127 line in `vendor/winter/storm/src/Database/Attach/Resizer.php` file - changing it to

`$alphaColor = imagecolorsforindex($this->image, $alphaIndex -1);`

or

`$alphaColor = imagecolorsforindex($this->image, $alphaIndex - 2);`

solved problem for some gif images. Seems that there should be additional check for image pallet size as described in linked [StackOverflow question](https://stackoverflow.com/questions/3874533/what-could-cause-a-color-index-out-of-range-error-for-imagecolorsforindex).

### PR DESCRIPTION
**Pull request by arvislacis**
Fixes https://github.com/wintercms/winter/issues/87
Testing or review is recommended.

### CODE REVIEW

**Comment by arvislacis** [comment]
Although pull request fixes https://github.com/wintercms/winter/issues/87, it seems that now there is problem with transparent gif files - gif files with transparency now lose some part of transparency after crop or resize. I will try to take closer look to address this issue.

**Comment by LukeTowers** [comment]
@arvislacis let us know when it's ready for review!

**Comment by arvislacis** [comment]
@LukeTowers It's ready for review, my last commit for this pull requested fixed the problem with transparent images and test cases. Anyways, additional review and check is welcome.

Short version of problem and created fix - sometimes transparency color index could be set outside an image pallet because index of the transparency color is property of image (not the color pallet) so this pull request gets the total number of colors in image pallet and compare that with returned transparency color index. If index is smaller than pallet size then transparency color index value is used (code is executed as before fix), if index is equal or larger than pallet size then transparency color fallback to the default value - 0 and no `Argument #2 ($color) is out of range` error is thrown.

**Comment by LukeTowers** [comment]
@arvislacis excellent! Thanks for the explanation and the fix! Would you be willing to add an image that the original code had problems with and this change fixes as a test case so the problem stays solved? :)

**Comment by arvislacis** [comment]
@LukeTowers @bennothommo While doing some additional tests at my end - I find out that there is another issue with GIF resizing (it's not related to my fix and this problem exists in v1.1.2) - after gif rezing (if there is no transparent color set) the white color of GIF image is replaced with transparent/alpha color.

For example:
- Input file: https://bb.ala.lv/storage/app/media/gif_tests/bg.gif
- Output file after `$resizer->resize(300, 255)`: https://bb.ala.lv/storage/app/media/gif_tests/testBgResize300x255.gif - the white color has become transparent.

^ I may try to fix also that but are you aware of this issue too?

**Comment by arvislacis** [comment]
@LukeTowers @bennothommo Added test cases and also additional fix for the issue I mentioned in my last message (which was not related to my changes and initial pull request).

**Comment by LukeTowers** [comment]
@arvislacis awesome! Thanks a ton for the help!

**Pull request merged**
