### PR TITLE
Pass _current_locale for queued translations

### PR DESCRIPTION
**Pull request by AIC-BV**

### CODE REVIEW

**Comment by bennothommo** [comment]
@AIC-BV thanks for the PR, but unless I'm mistaken, we're already handling the locale via this commit:
https://github.com/wintercms/storm/commit/cad4765de74805c3d9de538e5e811981a9610f67

October didn't have it in their October v2 branch because they nuked most of our changes.

**Comment by AIC-BV** [comment]
> @AIC-BV thanks for the PR, but unless I'm mistaken, we're already handling the locale via this commit: [cad4765](https://github.com/wintercms/storm/commit/cad4765de74805c3d9de538e5e811981a9610f67)
> 
> October didn't have it in their October v2 branch because they nuked most of our changes.

Yes, I was looking to remove the commit but I have no idea how.. I noticed that you guys are already handling this! Sorry!

**Comment by bennothommo** [comment]
@AIC-BV no problem, we appreciate the thought :)

**Comment by AIC-BV** [comment]
If i'm not wrong, I think that my issue is not yet solved: https://github.com/wintercms/winter/discussions/327

**Pull request closed without merging**
