### PR TITLE
Added additional test case for UrlGenerator class

### PR DESCRIPTION
**Pull request by arvislacis**
I tested the latest https://github.com/wintercms/storm/commit/32df10c002b7b522bdac054fc991d74b73533f98 commit and it seems that issues described in https://github.com/wintercms/wn-translate-plugin/issues/36 is not solved.

So I added additional test case.

### CODE REVIEW

**Comment by arvislacis** [comment]
Added test cases fail so issue still exists (or I made super dummy mistake in these tests).

https://github.com/wintercms/wn-translate-plugin/issues/36 issue also mostly focus about this case because although initial filter URL is like `https://www.example.com/path?array[]=v1&array[]=v2` - later it gets replaced to `https://www.example.com/path?array[0]=v1&array[1]=v2` because of language switch component... `https://www.example.com/path?array[]=v1&array[]=v2` and `https://www.example.com/path?array[0]=v1&array[1]=v2` is same but `Redirect::to()` then translates it to `https://www.example.com/path?array[0][]=v1&array[1][]=v2` which is not correct.

**Comment by mjauvin** [comment]
I confirm.

**Comment by mjauvin** [comment]
@arvislacis please add this to this PR, I think it fixes the issue:
```diff
diff --git a/src/Router/UrlGenerator.php b/src/Router/UrlGenerator.php
index 5c6f4a8..7268b46 100644
--- a/src/Router/UrlGenerator.php
+++ b/src/Router/UrlGenerator.php
@@ -326,7 +326,7 @@ public static function buildStr(array $query, string $prefix = '', $argSeparator
             if ($i === $k) {
                 if ($prefix) {
                     // Make sure the key is setup for array values
-                    if (Str::endsWith($prefix, '[]')) {
+                    if (Str::endsWith($prefix, ']')) {
                         $key = $prefix;
                     } else {
                         $key = "{$prefix}[]";
```

**Comment by arvislacis** [comment]
@mjauvin Done in https://github.com/wintercms/storm/pull/90/commits/5be073cf1bda7638693a609de4b734080e5579ca As far as I tested then this solves my issue (https://github.com/wintercms/wn-translate-plugin/issues/36) but I would suggest someone else also to take look.

Also added another test case (https://github.com/wintercms/storm/pull/90/commits/f329c19f28dedce3b79eea6619f5943c64ced52b) for https://github.com/wintercms/storm/blob/32df10c002b7b522bdac054fc991d74b73533f98/src/Router/UrlGenerator.php#L341

^ Everything is fine for this, I think test cases wouldn't be bad.

Probably there could also be tests for https://github.com/wintercms/storm/blob/32df10c002b7b522bdac054fc991d74b73533f98/src/Router/UrlGenerator.php#L332 and https://github.com/wintercms/storm/blob/32df10c002b7b522bdac054fc991d74b73533f98/src/Router/UrlGenerator.php#L336 although at the moment I couldn't think of any real life examples.

**Comment by arvislacis** [comment]
@mjauvin A little bit off-topic but is there any particular reason Winter CMS has implemented it's own URL processing and decoding, encoding and not using the Laravel one? I understand that users are nasty and can insert a lot of interesting things in URLs so decoding/encoding and additional processing may avoid this.

For example, if we look at my Locale Switcher case then for some users it also may look strange that `[]` gets encoded and displayed as `%5B0%5D` - of course that's nothing too critical but still...

**Comment by LukeTowers** [comment]
@arvislacis it's because Laravel does not do any of the parsing or url encoding / decoding of URLs that Winter is doing. There is no guarantee in Laravel when you passing a value to `Url::to()` (or any variation) that you will get a valid, safe URL back. 

I personally wanted a helper that would guarantee that the output generated by it was a spec-following URL that could be safely used in element attributes and anywhere else you might need a URL without worrying about potential injection attacks from users controlling part of or the entire URL.

**Comment by arvislacis** [comment]
@LukeTowers Thanks for clarification.

**Comment by LukeTowers** [comment]
Thanks for the help @arvislacis & @mjauvin!

**Pull request merged**
