### PR TITLE
Make extend() method usable with behaviors.

### PR DESCRIPTION
**Pull request by mjauvin**
Replaces #112 

```php
Model::extend(function ($model) {
    $model->behaviorMethodAvailable();
}, after: true);
```

Related: https://github.com/wintercms/docs/pull/98

### CODE REVIEW

**Comment by bennothommo** [comment]
@mjauvin I've tweaked the property names and did some clean up of the Extendable trait. Feel free to revert if you disagree with it all :)

**Comment by mjauvin** [comment]
So, who's in favor of merging this? Or something similar but through a seperate dedicated method ( e.g. `extendPostBehavior()` )

**Review by bennothommo — APPROVED** [review]

**Comment by LukeTowers** [comment]
@mjauvin are you needing this in 1.2.1 or are you fine with waiting for 1.2.2?

**Comment by mjauvin** [comment]
@LukeTowers I'm fine to wait for 1.2.2, which is why I moved it there.

**Comment by mjauvin** [comment]
Should I create a PR to the docs repo documenting this?

**Comment by bennothommo** [comment]
Just to note - this PR could be implemented via https://github.com/wintercms/storm/pull/134 instead if we wanted to go down that route.

@mjauvin's use case could be simply extending a particular instance  of the model locally via `$model->extend()`, which happens after instantiation and so other methods created by behaviors or other extensions would already be available.

**Comment by mjauvin** [comment]
> Just to note - this PR could be implemented via #134 instead if we wanted to go down that route.
> 
> @mjauvin's use case could be simply extending a particular instance of the model locally via `$model->extend()`, which happens after instantiation and so other methods created by behaviors or other extensions would already be available.

@bennothommo are you saying I could do:
```
MyModel::extend(function () {
    $this->extend(function () {
        $this->behaviorMethodAvailable();
    });
}, true);
```

And that `$this->behaviorMethodAvailbale()` call would work?

**Comment by mjauvin** [comment]
Close in favor of #134.

**Pull request closed without merging**
