### PR TITLE
Use fromRawAttributes() for custom pivot models

### LINKED ISSUE #741: Repeater field not initialzed properly pivot modal
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Test

### Issue description

If there is a relation widget with pivot model with a repeater type field, then in the pivot modal the repeater is always empty. If I enter some data to it and save it, the data is properly updated in the database, but upon opening the pivot modal the repeater is stil empty.

### Steps to replicate

Please see this PR: https://github.com/wintercms/wn-test-plugin/pull/11

### Workaround

_No response_

### PR DESCRIPTION
**Pull request by mjauvin**
Fixes https://github.com/wintercms/winter/issues/741

### CODE REVIEW

**Comment by mjauvin** [comment]
@hirisov if you could test this fix, that would be appreciated.

Thanks.

**Comment by mjauvin** [comment]
@bennothommo this should resolve the issue with the User's Roles awards in Winter.Test plugin as well.

**Comment by LukeTowers** [comment]
@mjauvin does line 838 also need to be changed?

**Comment by mjauvin** [comment]
> @mjauvin does line 838 also need to be changed?

I don't think so, but I'm not 100% sure.

**Comment by mjauvin** [comment]
> @mjauvin does line 838 also need to be changed?

According to the `newPivot()` method in Laravel's Eloquent Model, I think we're good:
```php
    public function newPivot(self $parent, array $attributes, $table, $exists, $using = null)
    {   
        return $using ? $using::fromRawAttributes($parent, $attributes, $table, $exists)
            : Pivot::fromAttributes($parent, $attributes, $table, $exists);
    }       
```

But I realize we could completely remove our overriden method now, since it's a carbon copy of Laravel's ...

**Comment by mjauvin** [comment]
See https://github.com/wintercms/storm/pull/185

**Comment by LukeTowers** [comment]
See https://github.com/wintercms/storm/pull/185#issuecomment-2258638874, our override is necessary to return our version of the Pivot model.

**Pull request merged**
