### PR TITLE
Ability to override existing relations 

### PR DESCRIPTION
**Pull request by goldmont**
[Discussion #1139](https://github.com/orgs/wintercms/discussions/1139)

@mjauvin

### CODE REVIEW

**Comment by LukeTowers** [comment]
@goldmont I'm not sure I'm comfortable with this approach. This also bypasses the check for a conflicting property and could have unintended side effects. 

IMO if a developer is going to be overriding an existing relationship then they need to be more explicit with that decision, in which case I think manually interacting with the original relationship definition is the best approach (which is how it was done before this method existed even just to add new relationships).

@bennothommo any thoughts from you on this?

**Comment by mjauvin** [comment]
@LukeTowers I would argue that specifying override:true is explicit enough...

**Comment by bennothommo** [comment]
I'm of the opinion that if you want to use a custom relation class, you add a separate relation. You don't override the original. The issue is that overriding the original basically sets you up for some feature to fail because it was expecting the original relation. You basically are forced to ensure that your custom relation class always sticks to the API of the original class it is overriding.

**Comment by LukeTowers** [comment]
> I would argue that specifying override:true is explicit enough...

I disagree, it encourages developers to always set it. The point of the helper method is to have this error checking in the first place: https://github.com/goldmont/storm/commit/b977610d361cc25f24b05062e40a83a6d53680a8

> Previously the developer would have to set the relation property directly themselves by merging their additions with the existing definitions and usually they wouldn't include any error checking logic

**Comment by LukeTowers** [comment]
Closing for now, will re-open if anyone has anything else to add to the discussion.

**Pull request closed without merging**
