### PR TITLE
Add nestedToArray to treecollection

### PR DESCRIPTION
**Pull request by damsfx**
Added a new method to the `TreeCollection` class to obtain the collection in a nested array.

In order to add a tree view mode to the checkboxlist formwidget, I need to be able to get the collection items as a nested tree.

```php
$tree = new Winter\Test\Models\Channel;
$tree->all();  // Winter\Storm\Database\TreeCollection

$tree->nestedArray(title', 'id'); 
// or 
$tree->all()->toNestedArray('title', 'id');
// return an nested array
[
    1 => [
      "title" => "Channel Orange",
      "children" => [
        2 => [
          "title" => "Autumn Leaves",
          "children" => [
            3 => [
              "title" => "September",
            ],
            4 => [
              "title" => "Winter",
            ],
            5 => [
              "title" => "November",
            ],
          ],
        ],
        6 => [
          "title" => "Summer Breeze",
        ],
      ],
    ],
    7 => [
      "title" => "Channel Green",
      "children" => [
        8 => [
          "title" => "Winter Snow",
        ],
        9 => [
          "title" => "Spring Trees",
        ],
      ],
    ],
  ]
  ```
  
Can be used with multiple column names to be returned in the array:
  ```php
 $tree->nestedArray(['title', 'description'], 'id'),
 // or 
$tree->all()->toNestedArray(['title', 'description'], 'id');
  ```
  Can also be used without key : 
  ```php
$tree->nestedArray(title'); 
// or 
$tree->all()->nestedToArray('title');
  
$tree->nestedArray(['title', 'description']),
// or 
$tree->all()->nestedToArray(['title', 'description']);
```

### CODE REVIEW

**Comment by LukeTowers** [comment]
Looks great @damsfx! Could you PR the docs as well?

**Comment by damsfx** [comment]
> Looks great @damsfx! Could you PR the docs as well?

https://github.com/wintercms/docs/pull/221 for the trait.
I don't really know how to describe the possible parameters.

For the `api/Winter/Storm/Database/TreeCollection` collection ... is documentation generated automatically?

**Comment by LukeTowers** [comment]
@damsfx yes: https://wintercms.com/docs/develop/api/Winter/Storm/Database/TreeCollection

**Comment by damsfx** [comment]
@LukeTowers I don't see the new `toNestedArray()` method on my side.

**Comment by LukeTowers** [comment]
@damsfx I think I need to look into what triggers it to regenerate the API docs

**Pull request merged**
